# Generated by Django 5.0 on 2023-12-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_most_viwed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='most_viwed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
