# Generated by Django 5.0 on 2023-12-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_address_order_name_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
