# Generated by Django 5.0 on 2023-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ON', 'Active'), ('OFF', 'Noactive')], default='OFF', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='most_viwed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
